# Change these first
owner: matiwiber # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ministerio de Seguridad
    url: https://www.mseg.gba.gov.ar 
  - name: Mi Portal 
    url: https://miportal.mseg.gba.gov.ar
  - name: Antecedentes
    url: https://antecedentes.mseg.gba.gov.ar
  - name: Subjefatura Policia
    url: www.policia.mseg.gba.gov.ar

assignees:
  - matiwiber
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  baseURL: /upptime
  # cname: demo.upptime.js.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
