# Change these first
owner: matiwiber # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository
# user-agent: matiwiber
sites:
  - name: Ministerio de Seguridad
    url: www.mseg.gba.gov.ar 
  - name: El Dia
    url: https://www.eldia.com/
  - name: Antecedentes
    url: https://antecedentes.mseg.gba.gov.ar
  - name: Infobae
    url: https://www.infobae.com/

# assignees:
  # - matiwiber
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  baseURL: /status-page
  # cname: demo.upptime.js.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Service
  introTitle: "**Status Service** es una pagina de estado que indica si los servicios estan activos"
  introMessage: This is a sample status page which uses **real-time**. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /status-page
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  
  i18n:
    footer: This is an open source repo createad for the Ministerio de Seguridad
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
